src/components/faq/faq-page.tsx
src/components/home/home-page.tsx
src/components/shared/layout.tsx
src/components/shared/mixin.tsx
src/components/shared/navigation-bar.tsx
src/components/verify/dropzone.tsx
src/components/verify/verify-page.tsx

- make columns responsive in pages

fix: responsive columns

---

public/index.html
src/components/faq/faq-page.tsx
src/components/home/home-page.tsx
src/components/shared/footer.tsx
src/components/shared/layout.tsx
src/components/shared/navigation-bar.tsx
src/components/verify/dropzone.tsx
src/components/verify/verify-page.tsx
src/tailwind.css
tailwind.config.js

- add Manjari, Roboto and Libre Franklin fonts
- replace div tags with header, paragraph tags
- keeping typography styles loose, h1 - h6 + p to use base styles in tailwind.css, as defined in typography styleguide

feat: add font

---

public/index.html
src/app.tsx
src/components/faq/faq-page.tsx
src/components/home/home-page.tsx
src/components/shared/footer.tsx
src/components/shared/layout.tsx
src/components/shared/scroll-to-top.ts
src/components/terms/terms-page.tsx
src/components/verify/dropzone.tsx
src/components/verify/verify-page.tsx
src/tailwind.css
tailwind.config.js

- add terms of use page
- consolidate all color variables in tailwind.config, import from there when necessary
- add meta title and description

feat: add terms of use page

---

public/index.html
src/components/faq/faq-page.tsx
src/components/shared/footer.tsx
src/components/shared/navigation-bar.tsx
src/components/terms/terms-page.tsx

- change all text instances of `verify.gov` to `verify.gov.sg`
- added content for faq page

chore: text changed

---

integration/certificate-issued-tampered-ropsten.json
integration/verified-issued-tampered.spec.ts
package-lock.json
package.json
src/components/verify/verify-page.tsx

- upgrade oa-verify
- change revoked check to hash check
- add test

feat: upgrade oa verify

---

integration/verified-unissued.spec.ts
src/components/verify/dropzone.tsx
src/components/verify/verify-page.tsx

- only set issuer name after the check on `DOCUMENT_STATUS` isValid
- if not isValid, wont show `Issued by` text entirely
- https://www.pivotaltracker.com/story/show/174485580

fix: issued by

---

src/components/shared/navigation-bar.tsx
src/components/verify/verify-page.tsx
src/types/index.tsx

- should be able to verify another doc when click on verify button again
- reset verificationStatus to idle when click on verify button
- reset verifying statues to PENDING at the beginning of verifying process

fix: verify another document

---

public/index.html
src/components/faq/faq-page.tsx
src/components/home/home-page.tsx
src/components/shared/header.tsx
src/components/shared/navigation-bar.tsx
src/components/verify/document-renderer.tsx
src/components/verify/verify-page.tsx
src/tailwind.css

- masthead, verify checks, generic alignments
- hover state to faq items
- smaller heading fonts in mobile

chore: alignment fixes

---

src/app.tsx
src/components/privacy/privacy-policy-page.tsx
src/components/shared/footer.tsx
src/components/terms/terms-page.tsx
src/tailwind.css

- add privacy policy page
- https://www.pivotaltracker.com/story/show/174647382

feat: privacy policy page

---

src/components/verify/verify-page.tsx

change decodeURI-to-decodeURIComponent

fix: decodeURI-to-decodeURIComponent

---

src/components/verify/verify-page.tsx

fix: change icon to red x

---

src/components/verify/verify-page.tsx
src/services/google-analytics.ts

https://www.pivotaltracker.com/n/projects/2464296
1. to change third check on verify site frontend text to "Issued by Singapore Government"
2. if cert is not issued by healthcerts.moh.gov.sg or moh.gov.sg, to change counter copy to "Document not issued by Singapore Government"

chore: edit issuer status display message

---

components/layout/Footer.tsx

- reduce font sizes for copyright text and version number in the footer
- make sublinks appear nicely in certain breakpoints

fix: footer tweaks

---

pages/contact.tsx

- swap order of links
- make the link copy ambiguous
- make oa contact us link shorter

fix: swap order of links

---

pages/terms.mdx

Corrected Description of Service to Schedule

chore: update terms.mdx header

---

components/figure/Renderer.tsx
components/verify/Verifier.tsx

Update renderDocument to send wrapped document to Renderer

feat: sent wrapped document to renderer

---

components/verify/Verifier.tsx

Add revocation message for DOCUMENT_STATUS

feat: add revocation message

---

integration/load-action-plain-certificate.spec.ts
tailwind.config.js
utils/error-handler.tsx
utils/notarise-healthcerts.ts

- Include `utils/*` folder for Tailwind compilation
- Create helper functions to detect Notarise and Notarise-SPM transient storage URLs
- Update fetch error message to something more readable for the casual user ~~depending on the transient storage URL~~

feat: update fetch error description

---

components/verify/Verifier.tsx
utils/google-analytics.test.tsx
utils/google-analytics.ts

feat: generic analytics for verification events

---

components/figure/VerificationChecks.tsx
components/verify/Verifier.tsx
integration/load-action-encrypted-certificate.spec.ts
integration/load-action-plain-certificate.spec.ts
integration/multi-tabs.spec.ts

- Replace existing first tick copy with 'Document has not been revoked' to be clear to MOP that it is issued and not revoked
- Replace 3rd tick VERIFIED message to 'Issued by the Singapore Government' if url ends with  'gov.sg'

feat: 185737190 enhance 1st and 3rd ticks

---

integration/multi-tabs.spec.ts
integration/qr-barcode-scanner.spec.ts

- Amend qr barcode scanner spec test to check for "Document has not been revoked" instead of "Document has been issued"

fix: qr barcode scanner spec test

---

components/layout/Footer.tsx
components/layout/NavigationBar.tsx
integration/multi-tabs.spec.ts

[Story link](https://www.pivotaltracker.com/story/show/185726596)
- change footer to SGDS, add links
- change navigation links.

Update footer to the SGDS footer

---

utils/google-analytics.test.tsx
utils/google-analytics.ts

In this PR:
- Add the issuer_name field when sending analytics events

chore: update ga4

---

package-lock.json

Update `ws` version due to vulnerability alerts.

fix: update ws dep
