package.json
Running the build command in parallel could led to the index.css to bot be created before being parsed by typescript (which then triggered an error `Cannot find file './index.css' in './src'.`)
=> fix: run build command in sequential

src/components/verify/dropzone.tsx
- omit cryptic error message
- https://www.pivotaltracker.com/story/show/174465988
- thought it was some utf-8 encoding issue (missing meta tag), but its not.
- interestingly, the error messages are reflected differently for different browsers, when using various file types (from left to right: chrome, firefox, safari)
- conclusion = to omit the message, log to console.error instead (not sure if its right) 😬
using jpg
using pdf
using mp4
=> fix: error message

src/app.tsx, src/components/faq/faq-page.tsx, src/components/home/home-page.tsx, src/components/privacy/privacy-policy-page.tsx, src/components/shared/masthead.tsx, src/components/shared/navigation-bar.tsx, src/components/terms/terms-page.tsx, src/components/verify/verify-page.tsx, src/tailwind.css, tailwind.config.js
- rename `Header` to `Masthead`
- set container spacing via config instead
- cross browser sticky footer fix (replace min-height with height)
issue: https://github.com/Open-Attestation/verify.gov.sg/issues/50
=> fix: sticky footer

src/components/shared/footer.tsx
- was nv a good idea to flex followed by flex
- only appears when access from mobile device
- this pr should fix the below:
=> fix: footer mobile

src/components/tabs.tsx
**Context**
Print button does not appear on mobile screens.
**Reason**
Allow users on mobile to perform "Print to PDF".
**Fixes**
- Always display print button
- Allow horizontal scroll of tabs on mobile
Demo: https://user-images.githubusercontent.com/37650399/117615332-293fe580-b19c-11eb-8542-447a61461cf7.mov
Printing tested on Android:
=> fix: display print button on mobile

integration/load-action-encrypted-certificate.spec.ts, src/components/verify/verify-page.tsx, src/services/retrieve-document.ts, src/types/index.tsx
In order to keep secrets on the client side, this PR adds the ability to obtain the `key` from the anchor in URLs.
Verify will attempt to extract the `key` in the following order:
1. Anchor: `Anchor.key`
2. Query params: `Action.payload.key`
For future extensibility, `Anchor` is an object that will be safely encoded and appended as a string in the URL:
```javascript
export interface Anchor {
key?: string;
}
```
```text
https://verify.gov.sg/verify?q={"query":"params"}#{"key":"secret"}
https://verify.gov.sg/verify?q=%7B%22query%22%3A%22params%22%7D%23%7B%22key%22%3A%22secret%22%7D
```
=> feat: obtain key from anchor

monitoring/infura.spec.ts
**What does this PR do?**
- Remove unnecessary selector waits
- Properly await for selectors to be visible first before proceeding
- Navigate to `verify.gov.sg` project (to ensure we are not looking at stats from other projects)
- Log `https://infura.io/api/stats/request-volume` instead as it has the original 24h time series we were relying on
=> fix: hourly monitoring of infura usage stats

components/layout/Footer.tsx
Disable the contact us link temporary until we know the next course of action
=> fix: disable contact us link

package-lock.json, package.json, tsconfig.json
1. Fix TypeScript compilation failure when running `npm run monitoring:
> **Error**
> ```
> Error: TypeScript compilation failed.
> /Users/kyle/repos/verify.gov.sg/monitoring/infura.spec.ts (1, 8): Module '"zlib"' has no default export.
> ```
> 
> **Fix**
> ```
> --compiler-options typescript.options.esModuleInterop=true
> ```
2. Ignore client-side JavaScript errors:
```
--skip-js-errors
```
3. Downgrade `node-fetch` to v2 as v3 is purely ESM
=> fix: monitoring compiler options

pages/contact.tsx
**Issue**
In the mobile view the oa support email link extends outside the box. (due to it being too long)
**Solution**
add css word break to force it to wrap.
=> fix: add word break for oa support email

monitoring/infura.spec.ts, package-lock.json, package.json
Temporarily set cookie to dismiss Sep 2022 modal that is overlaid on the Infura login page so that hourly monitoring test can proceed
=> fix: hourly monitoring being blocked by Infura modal

components/verify/Dropzone.tsx
Without a `/` in the front, the relative path will be appended after the existing path in the URL. To illustrate:
```url
https://www.verify.gov.sg/some/path
https://www.verify.gov.sg/some/path/images/logo.png
https://www.verify.gov.sg/images/logo.png
```
`/images/logo.png` will always be appended after the root domain (which is the behaviour we need for images).
=> chore: fix relative path for images

monitoring/infura.spec.ts
Temporarily set cookie to dismiss T&Cs modal that is overlaid on the Infura login page so that hourly monitoring test can proceed
Similar to #128
=> fix: hourly monitoring being blocked by t&c modal

components/figure/Renderer.tsx
- Checks for incompatible browsers and if user is printing from those browsers, prompt an alert box to let them know of the recommended browsers to use. Thereafter, print preview should show as per-normal (alert isn't a blocker)
- Referenced to the links below to check for Browser's User-Agent 
- SamsungBrowser (`SamsungBrowser`) - https://developers.whatismybrowser.com/useragents/explore/software_name/samsung-browser/
- iOS Chrome (`CriOS`) - https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome
- iOS FireFox (`FxiOS` - https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox
=> feat: add alert dialog for non-compatible browser printing

monitoring/infura.spec.ts
Hourly monitoring has been failing with `Could not find the stats` (i.e. `statsLogger` does not seem to be intercepting any HTTP requests)
- a12d68d06dcb35da94398d5f50fd98dc61c7ebf9 For debugging purposes, print out all the requests that have been captured when error is thrown (this helped to identify the above finding as an empty array `[]` was printed)
- 308518a0f6ba1860c7f8c94caf0702438f6d61cc Attach `statsLogger` to the fixture instead. For some reason, it does not capture HTTP requests when attached to test controller even though it is [a documented way](https://testcafe.io/documentation/402842/guides/advanced-guides/intercept-http-requests#attach-hooks-to-tests-and-fixtures)
=> test: fix hourly monitoring

.circleci/config.yml
=> chore: disable monitoring

components/verify/Verifier.tsx, utils/fixtures/pdt_v2_healthcert_ocsp_revoked.json, utils/fixtures/vac_v1_healthcert_eth_revoked.json
- `Document has been revoked` message has been shown too loosely (e.g. A document issued with a Mainnet document store (i.e. revocation store) will show as revoked if verification is performed against the Goerli network)
- In such cases, the message should just show: `Document has not been issued`
- Perform stricter checks on `isRevoked()` function instead of relying on `revokedOnAny` field (since `oa-verify` treats an unfound revocation store as revoked)
- This is achieved by:
1. Filtering for all invalid fragments
2. Extracting the document status fragment (either Ethereum document store issued or DID signed)
3. Checking the message for "has been revoked" text (ideal method not possible as explained in code comment)
1. [Ethereum-issued but revoked on Document Store …
=> feat: 183590615 stricter isRevoked checks

components/figure/Renderer.tsx, pages/verify.tsx
- Remove download button (accidentally added in #139)
- Add missing dependencies in React `useEffect()` or `useCallback()` hooks
=> fix: remove download button and add react hook dependencies

commitlint.config.js
Build fails because Commitlint says:
```text
✖   body's lines must not be longer than 100 characters [body-max-line-length]
```
- https://github.com/Open-Attestation/verify.gov.sg/pull/161
- https://circleci.com/gh/Open-Attestation/verify.gov.sg/14616
Add to Commitlint ignore when commit message is signed off by Dependabot:
```javascript
// commitlint.config.js
module.exports = {
...,
ignores: [(msg) => /Signed-off-by: dependabot\[bot\]/m.test(msg)],
};
```
Referencing from: https://github.com/dependabot/dependabot-core/issues/2445#issuecomment-949633412
=> ci: commitlint ignore Dependabot's commit messages

components/verify/CameraScanner.tsx, integration/qr-barcode-scanner.spec.ts, package-lock.json, package.json, pages/qr.tsx
QR camera scanner did not start automatically for some devices (e.g. iPhone) when the `react-qr-reader` library was used
- Replace ~~`react-qr-reader`~~ with `html5-qrcode`
- QR camera scanning is now the default mode
A race condition happens with the`html5-qrcode` library when React strict mode is enabled because [`useEffect()` is run twice](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state). We have the correct cleanup code `.stop()` but it seems to be called before the first render completes.
> To help surface these issues, React 18 introduces a new development-only check to Strict Mode. This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount.
As such, a …
=> fix: qr camera scanner does not automatically start for some devices

components/figure/Renderer.tsx
- Currently there are no way to fix the print issue for non-safari browsers on iOS devices ([reference: previous PR fix](https://github.com/Open-Attestation/verify.gov.sg/pull/140)). 
- Only Safari browser is able to show the correct behavior of print preview on iOS 
- We also found out that all other browsers on iOS (e.g. Brave, Edge, Chrome, Firefox) are having the same issue as well. Hence, this PR is to enable the alert on other non-safari browsers as well.
- Related tickets for future tracking - https://bugs.chromium.org/p/chromium/issues/detail?id=1421679 , https://bugs.chromium.org/p/chromium/issues/detail?id=1021034 
- Instead of showing pop up for iOS chrome and firefox, we are enabling the alert for all **non-safari browsers on iOS**
| Browser  | Filter keyword | Description | …
=> feat: show popup if user agent is iOS and a non-safari browser

components/verify/CameraScanner.tsx, pages/qr.tsx, utils/router-query-hook.ts
- Implementing QR scanner device selection via the `device` query param (e.g. `/qr?device=Back+Camera`, `/qr?device=Barcode+Scanner`, etc.)
- Currently, Google Analytics already keeps track of a `Page Referrer` property (i.e. `document.referrer`) on every page visit. By visiting `/verify` site, we will know which page the user originated from
- As such, we are riding on this existing behaviour by including a `device` query parameter to the URL so we can identify the scanner device (if any)
- Screenshot of Tag Assistant capturing Google Analytics event:
- `[SITE_URL, "https://www.verify.gov.sg"]` (SITE_URL is set in `next.config.js`)
- This will allow localhost or deploy preview QRs, especially useful for testing but will have no effect on production
1. Go to Tag Assistant: …
=> feat: 184378133 analytics for healthcerts verifications via qr scanner

.circleci/config.yml
- Pipeline failing because chromdriver fails to install; Related to this https://discuss.circleci.com/t/circleci-browser-tools-failing-on-chromedriver-116-x/49119/2 , seems to be resolved with circleci/browser-tools@1.4.5
- Update browser-tools to 1.4.5
=> chore: update circleci to pass chromedriver

next.config.js
- Since we have moved away from Netlify, we no longer have access to the Netlify build metadata's `CONTEXT`
- This directly impacts our [allowedOrigins whitelisting](https://github.com/Open-Attestation/verify.gov.sg/blob/master/pages/qr.tsx#L90)
- Removed Netlify related metadata and use `SITE_URL` from our environment variable directly
=> chore: use SITE_URL environment variable

pages/verify.tsx, utils/coded-error.ts, utils/error-handler.tsx, utils/notarise-healthcerts.test.ts, utils/notarise-healthcerts.ts
- Add error banner for HealthCerts using SPM or Notarise transient storage 
- To display the error only when certs are verified from a specific datetime onwards
- Add tests
=> chore: add healthcert transient storage error message

integration/multi-window-test/qr-barcode-scanner.spec.ts
- We are removing samples from schemata. Hence, a test that was referencing to the schemata was failing.
- Use gallery sample for barcode scanner test
=> test: replace schemata url with gallery for barcode test

integration/multi-window-test/qr-barcode-scanner.spec.ts, next.config.js
- Add `SITE_URL` environment variable to reference `process.env.NEXT_PUBLIC_SITE_URL` in NextJS config
=> chore: use correct env var

package-lock.json, package.json
* [This line imports ethers](https://github.com/Open-Attestation/verify.gov.sg/blob/772d635ea3ece50769855eb5769902f78e52b564/utils/oa-verify.ts#L15) but we dont have it in our package.json 
* Install ethers v5
=> chore: install ethers@5

components/layout/Masthead.tsx, next.config.js, package-lock.json, package.json, utils/google-analytics.ts
`@govtechsg/sgds-masthead-react` is deprecated
Use `@govtechsg/sgds-web-component` instead of `@govtechsg/sgds-masthead-react`
=> chore: use masthead from sgds web comp module instead

components/figure/Renderer.tsx, utils/google-analytics.test.tsx, utils/google-analytics.ts
Add GA tracking to the print button in the certificate viewer. 
- Add GA tracking to the print button
- Refactor the send GA event functions
- https://sgts.gitlab-dedicated.com/wog/gvt/gds-ace/general/dlt/galaxies-stories/trustdocs-stories/-/issues/301
=> feat: add ga tracking for print

pages/qr.tsx
Allow `https://www.trustdocs.gov.sg` and `https://action.openattestation.com` origins
=> feat: update whitelist for QR origins
